ci:
  autoupdate_schedule: quarterly
  autofix_commit_msg: pre-commit auto-fixes
  autoupdate_commit_msg: pre-commit autoupdate
  skip: [eslint, pyright]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        stages: [commit, commit-msg]
        exclude_types: [html, csv, bib]
        exclude: ^site/src/figs/.*$
        args: [--check-filenames, --ignore-words-list, "titel,fpr"]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
        # MD013: line too long
        # MD024: Multiple headings with the same content
        # MD033: no inline HTML
        # MD041: first line in a file should be a top-level heading
        # MD025: single title
        args: [--disable, MD013, MD024, MD025, MD033, MD041, "--"]

  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        args: [--drop-empty-cells, --keep-output]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args: [--write] # edit files in-place
        additional_dependencies:
          - prettier
          - prettier-plugin-svelte
          - svelte

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.9.0
    hooks:
      - id: eslint
        types: [file]
        args: [--fix, --config, site/eslint.config.js]
        files: \.(js|ts|svelte)$
        additional_dependencies:
          - eslint
          - svelte
          - typescript
          - eslint-plugin-svelte
          - typescript-eslint

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.376
    hooks:
      - id: pyright
        args: [--level, error]
