name: Test Scripts

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        script:
          - scripts/analysis/metrics_table.py
          - scripts/run_phonon_maker.py
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install package and dependencies
        run: pip install -e .[models]

      - name: Run script
        run: python ${{ matrix.script }}
