name: Tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version:
          - { python: "3.11", resolution: highest }
          - { python: "3.12", resolution: lowest-direct }
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version.python }}

      - name: Install dependencies
        run: |
          pip install uv
          uv pip install -e .[test] --system --resolution=${{ matrix.version.resolution }}

      - name: Run Tests
        run: pytest
