name: Test Scripts

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        script:
          - scripts/analysis/metrics_table.py
          - scripts/run_phonon_maker.py
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install package and dependencies
        run: |
          pip install uv
          # TODO remove with next atomate2 release fixing
          # TypeError: MACERelaxMaker.__init__() got an unexpected keyword argument 'calculator_kwargs'
          uv pip install --system git+https://github.com/materialsproject/atomate2
          uv pip install -e .[models] --system

      - name: Run script
        run: python ${{ matrix.script }}
